import React, {Component, PropTypes} from 'react'
import {reduxForm} from 'redux-form';
import metadataEvaluator from './lib/metadataEvaluator';
import modelParser from './lib/modelParser';
import { ButtonToolbar, Button } from 'react-bootstrap';
import clone from 'clone';


class AutoFormInternal extends Component {

    render() {

        let {
            componentFactory,
            fields, // this is not the fields passed from AutoForm. This is generated by ReduxForm. This object has a property for each field. Each property contains all redux props for the given field
            fieldMetadata,
            layout,
            handleSubmit,
            submitting
        } = this.props;

        let model = this.props.values;
        let modelCloned = clone(model); // I need to clone the model because I'm altering it
        modelParser.parse(fieldMetadata, modelCloned);
        let fieldMetadataEvaluated = metadataEvaluator.evaluate(fieldMetadata, modelCloned, '', fields);

        let groupComponent = componentFactory.buildGroupComponent({
            component: layout.component,
            layout: layout,
            fields: fieldMetadataEvaluated,
            componentFactory: componentFactory
        });

        // <button type="submit" disabled={submitting}>
        //     {submitting ? <i/> : <i/>} Submit
        // </button>

        return (
            <div className="meta-form">
                <form onSubmit={handleSubmit}>
                    { groupComponent }
                    <ButtonToolbar>
                        <Button type="submit" bsStyle="primary" disabled={submitting}>Submit</Button>
                        <Button disabled={submitting}>Cancel</Button>
                    </ButtonToolbar>
                </form>
            </div>
        )
    }
}

AutoFormInternal.propTypes = {
    fields: PropTypes.object.isRequired,
    handleSubmit: PropTypes.func.isRequired,
    resetForm: PropTypes.func.isRequired,
    submitting: PropTypes.bool.isRequired,
    componentFactory: PropTypes.object.isRequired,
    entity: PropTypes.object.isRequired,
    layout: PropTypes.object
};

export default reduxForm({
    form: 'simple'
})(AutoFormInternal);